name: latent_pose_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch==2.3.1
  - torchvision==0.18.1
  - pytorch-cuda==12.1
  - pip
  - pip:
    - transformers
    - pillow
    - matplotlib
    - numpy
    - opencv-python
    - scikit-learn
    - tqdm 